# ASSIGNMENT 3
<b>Question 1:</b> Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations.

In [40]:
import numpy as np
x=[1,2,3,4,5]
arr=np.array(x)
#1)-(a)
arr_sum=arr+2
print(arr_sum)
#1)-(b)
arr_multiply=arr*3
print(arr_multiply)
#1)-(c)
arr_div=arr/2
print(arr_div)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


<b>Question 2:</b> Questions on Basic NumPy Array.

In [48]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent = np.bincount(x).argmax()  
indices = np.where(x == most_frequent)[0]  
print(f"Most frequent value: {most_frequent}, Indices: {indices}")


Most frequent value: 1, Indices: [0 5 7 8 9]


In [50]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent = np.bincount(y).argmax()  
indices = np.where(y == most_frequent)[0]  
print(f"Most frequent value: {most_frequent}, Indices: {indices}")


Most frequent value: 1, Indices: [0 1 2]


<b>Question 3:</b> For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows.

In [31]:
#3)
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# a) Accessing the element at the first row and second column
element_1_2 = arr[0][1]
print("Element at (1st row, 2nd column):", element_1_2)
# b) Accessing the element at the third row and first column
element_3_1 = arr[2][0]
print("Element at (3rd row, 1st column):", element_3_1)


Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


<b>Question 4:</b> Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute? 

In [35]:
#4)
Ayush_C=np.linspace(10,100,25)
print(Ayush_C)
print("\nDimensions:",Ayush_C.shape)
print("\nTotal elements:",Ayush_C.size)
print("\nData Type of each element:",Ayush_C.dtype)
print("\nTotal Number of bytes consumed:",Ayush_C.itemsize*Ayush_C.size)
print("\nTranspose:\n",Ayush_C.reshape(25))
Ayush_C.T
print("\nYes,we can do the Transpose of this array using T attribute")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: (25,)

Total elements: 25

Data Type of each element: float64

Total Number of bytes consumed: 200

Transpose:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Yes,we can do the Transpose of this array using T attribute


<b>Question 5:</b> Create a 2-D Array of three rows and four columns, named ucs420_<<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<<your_name>>.

In [38]:
UCS420_Ayush=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("Mean:",np.mean(UCS420_Ayush))
print("\nMedian:",np.median(UCS420_Ayush))
print("\nMax:",np.max(UCS420_Ayush))
print("\nMin:",np.min(UCS420_Ayush))
print("\nUnique elements:",np.unique(UCS420_Ayush))
reshaped_UCS420_Ayush=UCS420_Ayush.reshape(4,3)
print("\n",reshaped_UCS420_Ayush)
resized_UCS420_Ayush = np.resize(UCS420_Ayush, (2, 3))
print("Resized array (2 rows*3 columns):\n",resized_UCS420_Ayush)

Mean: 43.333333333333336

Median: 37.5

Max: 90

Min: 10

Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2 rows*3 columns):
 [[10 20 30]
 [40 50 60]]
